### ISSUE TITLE
Add required notice for captcha labels

### ISSUE THREAD

**Issue by flowdee** [folkhack/Gravity-Forms-No-CAPTCHA-reCAPTCHA#5]
Right now the captcha fields are technically required but the label doesn't show the required asterisk *

@folkhack can you please add this as well? Would be amazing :+1:

**Comment by spenserhale** [comment]
@flowdee I added the required attribute to field, going to test to confirm but thats all it should need.
https://github.com/spenserhale/Gravity-Forms-No-CAPTCHA-reCAPTCHA/commits/spenser-corrections

**Comment by flowdee** [comment]
That's not what I need. As you can see on the screenshot below, the label of the Captcha should be required and include the *, which is not present right now but the captcha is definately a required field.

![Captcha Required](http://s21.postimg.org/lptlv2wpj/captcha_required.jpg)
